Optimizations update

diff --git a/files/initramfs/local-bottom/growroot b/files/initramfs/local-bottom/growroot
--- a/files/initramfs/local-bottom/growroot
+++ b/files/initramfs/local-bottom/growroot
@@ -18,7 +18,8 @@ esac
 
 . /scripts/functions
 
-msg() { echo "GROWROOT:" "$@" ; }
+#~ msg() { echo "GROWROOT:" "$@" ; }
+msg() { [ -f /bin/plymouth ] && plymouth update --status="GROWROOT: $@" ||  echo "GROWROOT:" "$@" ; }
 fail() { [ $# -eq 0 ] || msg "$@"; exit 1; }
 
 ###
@@ -110,14 +111,14 @@ fi
 udevadm settle --timeout ${ROOTDELAY:-30}
 
 echo "GROWROOT : E2FSCK ${rootdev}"
-e2fsck -p -f ${rootdev} >> /dev/null || fail "e2fsck failed"
+e2fsck -p -f ${rootdev} >> /dev/null && msg "e2fsck success" || fail "e2fsck failed"
 
 FSTYPE=$(get_fstype "${ROOT}")
 roflag="-w"
 mount ${roflag} ${FSTYPE:+-t ${FSTYPE} }${ROOTFLAGS} ${ROOT} ${rootmnt} || fail "failed to re-mount ${ROOT}. this is bad!"
 
 echo "GROWROOT : RESIZE2FS ${rootdev}"
-resize2fs ${rootdev} >> /dev/null || fail "resize2fs failed"
+resize2fs ${rootdev} >> /dev/null && msg "resize2fs success" || fail "resize2fs failed"
 
 # There was something to do, unmount and resize
 umount "${rootmnt}" ||	fail "failed to umount ${rootmnt}";
